"""add recorded_start_ts to videos

Revision ID: a1e5035b95d5
Revises: c0c513e6ca91
Create Date: 2025-12-30 10:54:18.215143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e5035b95d5'
down_revision: Union[str, Sequence[str], None] = 'c0c513e6ca91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('recorded_start_ts', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'recorded_start_ts')
    # ### end Alembic commands ###
