"""processing schema

Revision ID: c0c513e6ca91
Revises: 4b3b2960cbe7
Create Date: 2025-12-29 23:24:27.696384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0c513e6ca91'
down_revision: Union[str, Sequence[str], None] = "4b3b2960cbe7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('punch_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('punch_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_minutes', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('anomalies_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'business_date', 'employee_id', name='uq_attendance_store_date_employee')
    )
    op.create_index(op.f('ix_attendance_daily_business_date'), 'attendance_daily', ['business_date'], unique=False)
    op.create_index(op.f('ix_attendance_daily_employee_id'), 'attendance_daily', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_daily_store_id'), 'attendance_daily', ['store_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_business_date'), 'videos', ['business_date'], unique=False)
    op.create_index(op.f('ix_videos_camera_id'), 'videos', ['camera_id'], unique=False)
    op.create_index(op.f('ix_videos_sha256'), 'videos', ['sha256'], unique=False)
    op.create_index(op.f('ix_videos_store_id'), 'videos', ['store_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), server_default='v1', nullable=False),
    sa.Column('model_versions_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('PENDING','RUNNING','POSTPROCESSING','DONE','FAILED','CANCELED')", name='ck_jobs_status'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_video_id'), 'jobs', ['video_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type in ('csv','pdf','json')", name='ck_artifacts_type'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('entrance_id', sa.String(length=64), nullable=True),
    sa.Column('track_key', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('snapshot_path', sa.Text(), nullable=True),
    sa.Column('is_inferred', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type in ('entry','exit')", name='ck_events_event_type'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_employee_id'), 'events', ['employee_id'], unique=False)
    op.create_index('ix_events_employee_id_ts', 'events', ['employee_id', 'ts'], unique=False)
    op.create_index(op.f('ix_events_job_id'), 'events', ['job_id'], unique=False)
    op.create_index('ix_events_job_id_ts', 'events', ['job_id', 'ts'], unique=False)
    op.create_table('metrics_hourly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('hour_start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('exits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unique_visitors', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_dwell_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'hour_start_ts', name='uq_metrics_job_hour')
    )
    op.create_index(op.f('ix_metrics_hourly_job_id'), 'metrics_hourly', ['job_id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('track_key', sa.String(length=64), nullable=False),
    sa.Column('entrance_id', sa.String(length=64), nullable=True),
    sa.Column('first_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('best_snapshot_path', sa.Text(), nullable=True),
    sa.Column('assigned_type', sa.String(length=32), server_default='unknown', nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('identity_confidence', sa.Float(), nullable=True),
    sa.Column('first_seen_zone', sa.String(length=16), nullable=True),
    sa.Column('last_seen_zone', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assigned_type in ('employee','visitor','unknown')", name='ck_tracks_assigned_type'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'track_key', name='uq_tracks_job_track_key')
    )
    op.create_index(op.f('ix_tracks_employee_id'), 'tracks', ['employee_id'], unique=False)
    op.create_index(op.f('ix_tracks_job_id'), 'tracks', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_job_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_employee_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_metrics_hourly_job_id'), table_name='metrics_hourly')
    op.drop_table('metrics_hourly')
    op.drop_index('ix_events_job_id_ts', table_name='events')
    op.drop_index(op.f('ix_events_job_id'), table_name='events')
    op.drop_index('ix_events_employee_id_ts', table_name='events')
    op.drop_index(op.f('ix_events_employee_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_jobs_video_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_videos_store_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_sha256'), table_name='videos')
    op.drop_index(op.f('ix_videos_camera_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_business_date'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_attendance_daily_store_id'), table_name='attendance_daily')
    op.drop_index(op.f('ix_attendance_daily_employee_id'), table_name='attendance_daily')
    op.drop_index(op.f('ix_attendance_daily_business_date'), table_name='attendance_daily')
    op.drop_table('attendance_daily')
    # ### end Alembic commands ###
